### ISSUE TITLE
Checkboxes are tiny

### ISSUE THREAD

**Issue by Pummelfisch** [ceciliamay/obsidianmd-theme-primary#107]
Hey first I wanted to tell you that I realy love the clean yet useful design of the theme. So first of all thank you very much for all your work.
Since the newest update the checkboxes seem to be realy tiny. Not quite sure if thats a bug or intentionaly, but judging from the images on the main-page here on git a assume they are not supposed to be that way.
Added a picture with the two last checkboxes marked in red so you can understand what i mean.
Platform is Windows and I'm running Obsidian Version v0.14.4

![tiny checkboxes issue](https://user-images.githubusercontent.com/67376951/161110716-576f8355-d003-42bb-9d9a-417f8d77b9f1.png)

**Comment by corinnekaryiu** [comment]
Hey @Pummelfisch. I had the same issue.

This seems to be because the Obsidian insider version released today changed the variable `--editor-font-size` to `--font-text-size`. The checkboxes used the old variable name for sizing. It also affects icons inserted via the Icon Shortcodes plugin.

I've managed to fix it for now by adding this into a CSS snippet.

```
/* Fix font sizes */
* {
  --editor-font-size: var(--font-text-size);
}
```

Hopefully the Primary theme will be updated to account for the new variable name soon!

**Comment by ceciliamay** [comment]
Just finished pushing an update!! Should be working now 👍 Thanks for reporting!! Thank you for offering a quick fix for this, @corinnekaryiu !!

**Comment by spcbfr** [comment]
The checkboxes are still tiny even after using @corinnekaryiu 's snippet, I am on Obsidian V0.14.2

**Comment by WebInspectInc** [comment]
Still broken for me too, but only on iPhone. iPhone version is v1.1.1 (API v0.13.33)

I added this CSS snippet, which seems to fix it:

```
:root {
	--editor-font-size: 20px;
	--font-text-size: 20px;
}
```

Seems like something that may be fixed once the iPhone app updates to the latest version, perhaps.
