### ISSUE TITLE
[Feature Request] Reduce height of link suggestions on mobile

### ISSUE THREAD

**Issue by Signynt** [ceciliamay/obsidianmd-theme-primary#22]
Currently the suggestion box on mobile, that suggests links to add, obstructs the link you are trying to write (unless you are on the very top of the note). The minimal theme uses this code to prevent this from happening:

```
.is-mobile .suggestion-container {
    max-height:200px;
}
```

I've tested out this as a snippet and it works great, so it'd be really useful if this could be added to the theme itself!

**Comment by ceciliamay** [comment]
This is now fixed in [Release v.0.2.7](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.0.2.7) !! ✨🎉

**Comment by Signynt** [comment]
@ceciliamay Awesome, this has fixed the issue on my phone for me!
Unfortunatly it is still present on iPad for some reason… 

Here’s the search suggestions with the snippet enabled:
![697E3AEC-C684-4628-AEB0-7F599032C39F](https://user-images.githubusercontent.com/67801159/143418711-392324ea-c48a-445b-9283-d587f7ee45f3.png)

And here it is without the snippet in the newest version of the theme:
![E3CD7F8A-0003-4881-A2B9-E6D00AD9579C](https://user-images.githubusercontent.com/67801159/143418715-9e1dc476-f1f6-4441-9f83-f2b2d56dd02d.png)

**Comment by ceciliamay** [comment]
I tried fixing this! It's now at v.1.0! Please update your theme and check it out! [Here's the changelog.](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.0.0)
