### ISSUE TITLE
Latest update breaks default configuration of Supercharged Links

### ISSUE THREAD

**Issue by HEmile** [ceciliamay/obsidianmd-theme-primary#51]
Hi! In the latest update, the colouring of internal links in Primary gets a higher priority than the styling from the Supercharged Links plugin: https://github.com/mdelobelle/obsidian_supercharged_links , despite the fact that I have added !important to the color attribute. Is it possible to decrease the priority here? 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1289165/151128842-dd0ef0e5-b3d7-47d0-9394-9e36825957a5.png">

![image](https://user-images.githubusercontent.com/1289165/151129572-7b6fb05c-e035-4235-8b8a-aa593d7bb413.png)

<img width="315" alt="image" src="https://user-images.githubusercontent.com/1289165/151129500-e64d1258-f5fc-4ddb-b867-8cb55f99b828.png">

**Comment by HEmile** [comment]
This snippet seems to fix it for me. Replace the section under Internal & External links (1828) 
https://gist.github.com/HEmile/6582660e25622ad3085734d49b27f260

**Comment by ceciliamay** [comment]
Fixed this issue in [Release v.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.1.0)! Lowered the specificity as suggested and went for a better CSS property for the underlines. 🎉✨

**Comment by HEmile** [comment]
Thanks! This seems to have helped for the preview mode, but I still cannot get to style the live preview mode

**Comment by ceciliamay** [comment]
Tried to fix it again! Update your theme and let me know how it goes!

I can't remove the underline though - the supercharged links are deeply tied to `.cm-hmd-internal-link` which I use to style Internal Links. So for now, it has an underline but it matches the color set by the user for the super link. Please let me know if there are any more issues! I'm planning to add an option to remove underlines in the future 😄

**Comment by HEmile** [comment]
This seems to have worked! Thank you so much ^^
